"""Change delivery_id column to recieve string no integer

Revision ID: d8e91adf581b
Revises: fe88895682bd
Create Date: 2026-04-17 14:31:18.982053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e91adf581b'
down_revision: Union[str, Sequence[str], None] = 'fe88895682bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('github_events', 'delivery_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('github_events', 'delivery_id',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
